Messages:
  teleportPerms: '&8[&a#&8]: &fУ вас отсутствует доступ в мир &a%WORLD%&f.'
  joinPerms: '&8[&a#&8]: &fУ вас отсутствует доступ в мир &a%WORLD%&f. Вы перемещены на спавн.'
  specBreakFailed: '&8[&a#&8]: &fВы не можете разрушать блоки в этом мире.'
  specPlaceFailed: '&8[&a#&8]: &fВы не можете размещать блоки в этом мире.'
  specDamageFailed: '&8[&a#&8]: &fВы не можете повреждать сущности в этом мире.'
  specCommandFailed: '&8[&a#&8]: &fДоступные команды &a/spawn, /back, /wol, /home'
  specDropFailed: '&8[&a#&8]: &fВы не можете выбрасывать вещи в этом мире.'
  editPerms: '&8[&a#&8]: &fУ вас не достаточно полномочий чтобы выполнить команду в этом мире.'
  cmdSpawnWorldNotExist: '&8[&a#&8]: &fУказанный мир &a%WORLD%&f не найден.'
  cmdNotWorldErr: '&8[&a#&8]: &fДанную команду нужно выполнять в активированных мирах.'
  yourSelfDeleteErr: '&8[&a#&8]: &fВы не можете себя удалить из списка мира.'
  dontHavePermissions: '&8[&a#&8]: &fУ вас недостаточно прав для выполнения данной команды.'
  cmdSpawnSucc: '&8[&a#&8]: &fВы успешно перемещены на локацию спавна.'
  remWorldSucc: '&8[&a#&8]: &fИгрок &a%PLAYER% &fуспешно удален из списка мира.'
  remWorldNotF: '&8[&a#&8]: &fИгрок &a%PLAYER% &fне найден в мире.'
  addWorldSucc: '&8[&a#&8]: &fИгрок &a%PLAYER% &fуспешно добавлен в список мира.'
  remWorldMsg1: '&8[&a#&8]: &fИгрок &a%PLAYER% &fудалил вас из мира &a%WORLD%&f. Вы перемещены на спавн.'
  remWorldMsg2: '&8[&a#&8]: &fИгрок &a%PLAYER% &fудалил вас из мира &a%WORLD%&f.'
  areWorldAdded: '&8[&a#&8]: &fИгрок &a%PLAYER% уже находится в списке мира.'
  setWorldPl: '&8[&a#&8]: &a%PLAYER% &fтеперь тип игрока &a%TYPE%&f.'
  setWorldAre: '&8[&a#&8]: &a%PLAYER% &fуже имеет этот тип.'
  setWorldToPl: '&8[&a#&8]: &a%PLAYER% &fустановил вам тип игрока &a%TYPE% &fв мире &a%WORLD%&f.'
  addWorldToPl: '&8[&a#&8]: &fВы были добавлены в мир &a%WORLD% &fигроком &a%PLAYER% &fв группу наблюдателей.'
  cmdSetSpawnSucc: '&8[&a#&8]: &fТочка спавна в мире &a%WORLD% &fуспешно установлена на ваших текущих координатах: X: &a%X% &fY: &a%Y% &fZ: &a%Z%'
  playerNotExists: '&8[&a#&8]: &fИгрок &a%PLAYER% &fдолжен быть на сервере.'
  cmdActiveAdvMode: '&8[&a#&8]: &fУлучшенный режим успешно активирован.'
  cmdActiveAdvModeAll: '&8[&a#&8]: &a%PLAYER% &fактивировал улучшенный режим. Доступ к этому миру будет ограничен если все владельцы покинут игру.'
  cmdDeactiveAdvMode: '&8[&a#&8]: &fУлучшенный режим успешно деактивирован.'
  cmdDeactiveAdvModeAll: '&8[&a#&8]: &a%PLAYER% &fдеактивировал улучшенный режим.'
  cmdOnlyPlayer: '&8[&a#&8]: &fТолько игрок может выполнять команду.'
  cmdOnlyConsole: '&8[&a#&8]: &fТолько игрок может выполнять команду.'
  cmdNotAllowChangeType: '&8[&a#&8]: &fВы не можете изменять тип этого игрока.'
  cmdChangeModePublic: '&8[&a#&8]: &fПубличный режим успешно активирован.'
  cmdChangeModePublicAll: '&8[&a#&8]: &a%PLAYER% &fактивировал публичный режим в мире &a%WORLD%&f. Любой игрок может модифицировать его.'
  cmdChangeModeAccess: '&8[&a#&8]: &fЗакрытый режим успешно активирован.'
  cmdChangeModeAccessAll: '&8[&a#&8]: &a%PLAYER% &fактивировал закрытый режим в мире &a%WORLD%&f.'
  cmdChangeModeIsActivated: '&8[&a#&8]: &aДанный режим уже активирован.'
  help: 
  - '&8--------------------------------------------------------------'
  - '&a/wol &8- &fПомощь по командам'
  - '&a/wol access&8- &fпросмотр доступа к мирам'
  - '&a/wol list&8- &fПросмотр списка всех игроков добавленные в мир'
  - '&a/wol players&8- &fПросмотр списка миров в которых в данный момент находятся игроки'
  - '&a/wol spawn <мир> &8- &fПеремещение на локацию спавна в указанном мире'
  - '&a/wol addplayer <игрок> &8- &fДобавить игрока в мир. Поумолчанию игрок станет наблюдателем.'
  - '&a/wol removeplayer <игрок> &8- &fУдалить игрока с мира.'
  - '&a/wol set <игрок> <тип> &8- &fУстановить тип доступа игроку. (Типы: spectator, member, moder)'
  - '&a/wol setspawn &8- &fУстановить точку спавна в мире'
  - '&a/wol player <ник> &8- &fПоказать информацию о добавленном игроке.'
  - '&a/wol advmode &8- &fПереключить режим строительства. (Если включено, при отсутствие владельца на сервере, любой игрок добавленный в мир, не сможет его модифицировать)'
  - '&a/wol accessmode &8- &fПереключить режим входа. (Если включено, любой игрок сможет войти в ваш мир)'
  - '&6Автор плагина &cBoomEaro. &6Версия: &c{version}'
  - '&8--------------------------------------------------------------'