name: WorldLister
main: ru.boomearo.worldlister.WorldLister
version: 0.11.1
author: BoomEaro
description: Plugin that divides the worlds by access
api-version: 1.13
softdepend: [MultiWorld, Multiverse-Core]
commands:
  worldlister:
    usage: /worldlist access|list
    aliases: [worldlist, wol]
    description: Main command